- name: Enable Versioning in Storage Account
  shell: az storage account blob-service-properties update --resource-group "{{ RG_name }}" --account-name "{{ storage_account_name }}" --enable-versioning