
- name: Provision a virtual machine on Azure
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: teshrgvm58
    vm_username: "riteshgupta"
    RG_name: RITESH-SP-RG
    virtual_network: testvn001
    sec_group: secgroup001
    subnet_name: subnet001

  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ RG_name }}"
      location: eastus

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ RG_name }}"
      name: "{{ virtual_network }}"
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ RG_name }}"
      name: "{{ subnet_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ virtual_network }}"

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ RG_name }}"
      allocation_method: Static
      name: "{{ vm_name }}_PublicIP"
    register: output_ip_address
    
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."

  - name: Create security group that allows SSH/HTTP/HTTPS
    azure_rm_securitygroup:
      resource_group: "{{ RG_name }}"
      name: "{{ sec_group }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 102
          direction: Inbound
        - name: HTTPS
          protocol: Tcp
          destination_port_range: 443
          access: Allow
          priority: 103
          direction: Inbound
          
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ RG_name }}"
      name: "{{ vm_name }}_NIC"
      virtual_network: "{{ virtual_network }}"
      subnet: "{{ subnet_name }}"
      public_ip_name: "{{ vm_name }}_PublicIP"
      security_group: "{{ sec_group }}"

  - name: Create Linux VM
    azure_rm_virtualmachine:
      resource_group: "{{ RG_name }}" 
      name: "{{ vm_name }}"
      vm_size: Standard_DS1_v2
      admin_username: "{{ vm_username }}"
      #admin_password: "{{ vm_password }}"
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/riteshgupta/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAwDT75h7+pehBphcdY2O7VA9B6wq9sq+FBEgbGemAhJa/MDGEaaYkM/Tt8VKU+Bs/AiQzqXTJBA8HbrRlNjW5rZlx0oQcqdju3+qV42CxyoaVsZuxdkeXyG0Sf3ia0oQvcDNchMchfPfJSAqaXZyj5z/UIGobemj6/MTbdwX1NnzYj6UyQL8T2sqLxAZhf1hEN54RjsmNZ+NRCXQwP8ctgVOxElbSaiWFTllP6hHElP8xrSSaK9/xC1YPZk6FYwj4WsH7OsoMA40nEFROPal6UolamXTBXiOfSrMIVw8ahcjISSzJLku/AVDYVuePEEaWtHzG7dX93+UKC3wfGFkPlIUlIEr4Sps0ZC2ChJpv0cCUQopdmJfMHg/rhC5N4yFyHX6uI0uQFGgEj7GG2QFdl52A92DGvhXZyeCXX2upfcBwvmXIsFBhPvVPrElLd90Z6B2yJyVkcWBt1NQ4rxgiHssxW3g7bWG7GdFMUwbf/e4LFUEQeHfu+RkToPYVscvV5t8a+MnfqZvlfXfw3PQ2W/8U/Wkf+PVC3twI2yhZp48SmF9p/MCBy25RjSJ6DxVBNEkITgZnjMk0uNjd/QqOGwVNfDnk24muNjd5XP+pnXzDn5OuWb18/pUw7H0qaG7Pibr0D0C6chH6rjcViWUUTgsOOearxEp6QK+/Z0T92w== riteshgupta@Riteshs-MacBook-Air.local"
      network_interfaces: "{{ vm_name }}_NIC"
      managed_disk_type: Standard_LRS
      # os_type defaults to linux, so specify windows if needed
      image:
        offer: 0001-com-ubuntu-server-focal
        publisher: canonical
        sku: 20_04-lts
        version: latest
      open_ports:
        - 22
        - 80
        - 443
  
