- name: Setup Encryption at rest
  hosts: localhost
  collections:
    - azure.azcollection
  vars:
    tenant_id: 8f0f669a-21e5-469b-93ea-29e4cd288d97
    object_id: 8efdeca6-5815-4388-bfac-d045fb1eadbc
    vault_name: testkvritesh685
    storage_account_name: clh00063
    resource_group: RITESH-SP-RG

  tasks:
    - name: create an account
      azure_rm_storageaccount:
        resource_group: "{{ resource_group }}"
        name: "{{ storage_account_name }}"
        type: Standard_RAGRS
        tags:
          testing: testing

    - name: Assign identity
      shell: az storage account update --name "{{ storage_account_name }}" --resource-group "{{ resource_group }}" --assign-identity

    - name: fetch object id of storage identity
      shell: az storage account show --name "{{ storage_account_name }}" --resource-group "{{ resource_group }}" --query identity.principalId --output tsv
      register: command_output

    - set_fact:
        string_to_echo: "{{ command_output.stdout }}"

    - debug: 
        var: string_to_echo

    - name: Create instance of Key Vault
      azure_rm_keyvault:
        resource_group: "{{ resource_group }}"
        vault_name: "{{ vault_name }}"
        enabled_for_deployment: yes
        vault_tenant: "{{ tenant_id }}"
        enable_purge_protection: yes
        sku:
          family: 'A'
          name: standard
        access_policies:
          - tenant_id: "{{ tenant_id }}"
            object_id: "{{ object_id }}"
            keys:
              - get
              - list
              - encrypt
              - decrypt
              - wrapkey
              - unwrapkey
              - create
              - update
              - delete
          - tenant_id: "{{ tenant_id }}"
            object_id: "{{ string_to_echo }}"
            keys:
              - get
              - list
              - encrypt
              - decrypt
              - wrapkey
              - unwrapkey
              - create
              - update
              - delete
    # # - name: Enable Versioning in Storage Account
    # #   shell: az keyvault key create --name testkey --vault-name testkvritesh588
    - name: Create a key
      azure_rm_keyvaultkey:
       key_name: "TestKey2"
       keyvault_uri: "https://{{ vault_name }}.vault.azure.net/"
       state: present

    - name: Enable Versioning in Storage Account
      shell: az storage account update --name "{{ storage_account_name }}" --resource-group "{{ resource_group }}" --encryption-key-name TestKey2 --encryption-key-source Microsoft.Keyvault --encryption-key-vault "https://{{ vault_name }}.vault.azure.net/"